entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      tls:
        certResolver: default
providers:
  docker:
    watch: true
    exposedByDefault: false
    network: web
log:
  level: DEBUG
ping: {}
api:
  dashboard: true
  insecure: false
accessLog: {}
certificatesResolvers:
  default:
    acme:
      email: ivaegjzod@mozmail.com
      storage: acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      tlsChallenge: {}
      dnsChallenge:
        provider: "acme-dns"
        resolvers:
          - "8.8.8.8:53"
